Import('*')

srcs = Split('jacobi.c symm.c symmv.c nonsymm.c nonsymmv.c herm.c hermv.c gensymm.c gensymmv.c genherm.c genhermv.c gen.c genv.c sort.c francis.c schur.c')
objs = env.Object(srcs)

libname = 'gsleigen'
lib = env.StaticLibrary(libname, objs)
env['PRJ_LIBS'][libname] = lib
env['PRJ_OBJS'][libname] = objs

exename = 'eigen_test'
exelibs = [
    lib,
    env['PRJ_LIBS']['gsllinalg'],
    env['PRJ_LIBS']['gslblas'],
    env['PRJ_LIBS']['gslcblas'],
    env['PRJ_LIBS']['gslpermutation'],
    env['PRJ_LIBS']['gslmatrix'],
    env['PRJ_LIBS']['gslvector'],
    env['PRJ_LIBS']['gslblock'],
    env['PRJ_LIBS']['gslrng'],
    env['PRJ_LIBS']['gslsort'],
    env['PRJ_LIBS']['gslcomplex'],
    env['PRJ_LIBS']['gslieeeutils'],
    env['PRJ_LIBS']['gsltest'],
    env['PRJ_LIBS']['gslerr'],
    env['PRJ_LIBS']['gslsys'],
    env['PRJ_LIBS']['gslerr'],
    #env['PRJ_LIBS']['utils'],
]
exe = env.Program(exename, 'test.c', LIBS=exelibs)
env['PRJ_EXES'][exename] = exe

