Import('*')

srcs = Split('qrng.c niederreiter-2.c sobol.c halton.c reversehalton.c inline.c')
objs = env.Object(srcs)

libname = 'gslqrng'
lib = env.StaticLibrary(libname, objs)
env['PRJ_LIBS'][libname] = lib
env['PRJ_OBJS'][libname] = objs

exename = 'qrng_test'
exelibs = [
    lib,
    env['PRJ_LIBS']['gslieeeutils'],
    env['PRJ_LIBS']['gsltest'],
    env['PRJ_LIBS']['gslerr'],
    env['PRJ_LIBS']['gslsys'],
    #env['PRJ_LIBS']['utils'],
]
exe = env.Program(exename, 'test.c', LIBS=exelibs)
env['PRJ_EXES'][exename] = exe

