Import('*')

srcs = Split('dd.c eval.c solve_quadratic.c solve_cubic.c zsolve_quadratic.c zsolve_cubic.c zsolve.c zsolve_init.c deriv.c')
objs = env.Object(srcs)

libname = 'gslpoly'
lib = env.StaticLibrary(libname, objs)
env['PRJ_LIBS'][libname] = lib
env['PRJ_OBJS'][libname] = objs

exename = 'poly_test'
exelibs = [
    lib,
    env['PRJ_LIBS']['gslsort'],
    env['PRJ_LIBS']['gslieeeutils'],
    env['PRJ_LIBS']['gsltest'],
    env['PRJ_LIBS']['gslerr'],
    env['PRJ_LIBS']['gslsys'],
    #env['PRJ_LIBS']['utils']
]
exe = env.Program(exename, 'test.c', LIBS=exelibs)
env['PRJ_EXES'][exename] = exe

