Import('*')

srcs = Split('dft.c fft.c')
objs = env.Object(srcs)

libname = 'gslfft'
lib = env.StaticLibrary(libname, objs)
env['PRJ_LIBS'][libname] = lib
env['PRJ_OBJS'][libname] = objs

exename = 'fft_test'
exelibs = [
    lib,
    env['PRJ_LIBS']['gslieeeutils'],
    env['PRJ_LIBS']['gsltest'],
    env['PRJ_LIBS']['gslerr'],
    env['PRJ_LIBS']['gslsys'],
    #env['PRJ_LIBS']['utils'],
]
exe_srcs = Split('test.c signals.c')
exe = env.Program(exename, exe_srcs, LIBS=exelibs)
env['PRJ_EXES'][exename] = exe

