Import('*')

srcs = Split('print.c make_rep.c env.c fp.c read.c')
objs = env.Object(srcs)

libname = 'gslieeeutils'
lib = env.StaticLibrary(libname, objs)
env['PRJ_LIBS'][libname] = lib
env['PRJ_OBJS'][libname] = objs

exename = 'ieeeutils_test'
exelibs = [
    lib,
    env['PRJ_LIBS']['gsltest'],
    env['PRJ_LIBS']['gslsys'],
    #env['PRJ_LIBS']['utils']
]
exe = env.Program(exename, 'test.c', LIBS=exelibs)
env['PRJ_EXES'][exename] = exe

