Import('*')

srcs = Split('sort.c sortind.c sortvec.c sortvecind.c subset.c subsetind.c')
objs = env.Object(srcs)

libname = 'gslsort'
lib = env.StaticLibrary(libname, objs)
env['PRJ_LIBS'][libname] = lib
env['PRJ_OBJS'][libname] = objs

exename = 'sort_test'
exelibs = [
    lib,
    env['PRJ_LIBS']['gslpermutation'],
    env['PRJ_LIBS']['gslvector'],
    env['PRJ_LIBS']['gslblock'],
    env['PRJ_LIBS']['gslieeeutils'],
    env['PRJ_LIBS']['gsltest'],
    env['PRJ_LIBS']['gslerr'],
    env['PRJ_LIBS']['gslsys'],
    #env['PRJ_LIBS']['utils']
]
exe = env.Program(exename, 'test.c', LIBS=exelibs)
env['PRJ_EXES'][exename] = exe

