Import('*')

srcs = Split('multiply.c exponential.c tridiag.c lu.c luc.c hh.c qr.c qrpt.c lq.c ptlq.c svd.c householder.c householdercomplex.c hessenberg.c hesstri.c cholesky.c choleskyc.c symmtd.c hermtd.c bidiag.c balance.c balancemat.c inline.c')
objs = env.Object(srcs)

libname = 'gsllinalg'
lib = env.StaticLibrary(libname, objs)
env['PRJ_LIBS'][libname] = lib
env['PRJ_OBJS'][libname] = objs

exename = 'linalg_test'
exelibs = [
    lib,
    env['PRJ_LIBS']['gslblas'],
    env['PRJ_LIBS']['gslcblas'],
    env['PRJ_LIBS']['gslpermutation'],
    env['PRJ_LIBS']['gslmatrix'],
    env['PRJ_LIBS']['gslvector'],
    env['PRJ_LIBS']['gslblock'],
    env['PRJ_LIBS']['gslcomplex'],
    env['PRJ_LIBS']['gslieeeutils'],
    env['PRJ_LIBS']['gsltest'],
    env['PRJ_LIBS']['gslerr'],
    env['PRJ_LIBS']['gslsys'],
    env['PRJ_LIBS']['gslerr'],
    #env['PRJ_LIBS']['utils']
]
exe = env.Program(exename, 'test.c', LIBS=exelibs)
env['PRJ_EXES'][exename] = exe

