Import('*')

srcs = Split('rstat.c rquantile.c')
objs = env.Object(srcs)

libname = 'gslrstat'
lib = env.StaticLibrary(libname, objs)
env['PRJ_LIBS'][libname] = lib
env['PRJ_OBJS'][libname] = objs

exename = 'rstat_test'
exelibs = [
    lib,
    env['PRJ_LIBS']['gslstatistics'],
    env['PRJ_LIBS']['gslrandist'],
    env['PRJ_LIBS']['gslspecfunc'],
    env['PRJ_LIBS']['gslcomplex'],
    env['PRJ_LIBS']['gslvector'],
    env['PRJ_LIBS']['gslsort'],
    env['PRJ_LIBS']['gslrng'],
    env['PRJ_LIBS']['gslieeeutils'],
    env['PRJ_LIBS']['gsltest'],
    env['PRJ_LIBS']['gslerr'],
    env['PRJ_LIBS']['gslsys'],
    #env['PRJ_LIBS']['utils'],
]
exe = env.Program(exename, 'test.c', LIBS=exelibs)
env['PRJ_EXES'][exename] = exe

